// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvG01ouliPPIGl5bG6_TDqEIaiydGbAlQ',
    appId: '1:340287144085:web:1b47c51b21ffe5f80fdb9c',
    messagingSenderId: '340287144085',
    projectId: 'food-menu-e85d6',
    authDomain: 'food-menu-e85d6.firebaseapp.com',
    storageBucket: 'food-menu-e85d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDe8xoYx6-vCbOGC2Hh0NGtHGrp2XHr4PE',
    appId: '1:340287144085:android:8f95587e95e8fe6f0fdb9c',
    messagingSenderId: '340287144085',
    projectId: 'food-menu-e85d6',
    storageBucket: 'food-menu-e85d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_RPdKFJyqNYoToaLIVUDAlyLVnmFXo4Y',
    appId: '1:340287144085:ios:30d100dbe3d4e6c50fdb9c',
    messagingSenderId: '340287144085',
    projectId: 'food-menu-e85d6',
    storageBucket: 'food-menu-e85d6.appspot.com',
    iosBundleId: 'com.example.foodMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_RPdKFJyqNYoToaLIVUDAlyLVnmFXo4Y',
    appId: '1:340287144085:ios:30d100dbe3d4e6c50fdb9c',
    messagingSenderId: '340287144085',
    projectId: 'food-menu-e85d6',
    storageBucket: 'food-menu-e85d6.appspot.com',
    iosBundleId: 'com.example.foodMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvG01ouliPPIGl5bG6_TDqEIaiydGbAlQ',
    appId: '1:340287144085:web:e9304df4027fe6200fdb9c',
    messagingSenderId: '340287144085',
    projectId: 'food-menu-e85d6',
    authDomain: 'food-menu-e85d6.firebaseapp.com',
    storageBucket: 'food-menu-e85d6.appspot.com',
  );
}
